### ISSUE TITLE
Seeds

### ISSUE THREAD

**Issue by closeshot** [cweckerl/simplefarming#66]
Forge-31.1.9

When trying to harvest rice seeds I only get the seeds back and not the actual rice seeds. Tried other  plants like pepper and ginger and I am getting both resources

**Comment by closeshot** [comment]
Just tried the harvester from cyclic and when its harvesting I'm getting the seed and the rice

**Comment by MamaArgie** [comment]
I'm having this issue as well. Not getting a few different crops, just the seeds from them. I don't have Harvest installed, so I have no work around.
