### ISSUE TITLE
Growing bushes do not post the CropGrowEvent

### ISSUE THREAD

**Issue by daPoseidonGuy** [cweckerl/simplefarming#91]
**Forge Version**
1.15.2 - 31.2.31

**Mod list (optional)**
My mod - strawgolem reborn + this one

**Log file (optional)**
n/a

**Describe the issue**

EDITED:

Never mind, I'm an idiot

**Comment by daPoseidonGuy** [comment]
I closed it in a moment of confusion - the issue stands.
https://github.com/cweckerl/simplefarming/blob/1.15/src/main/java/enemeez/simplefarming/block/growable/BerryBushBlock.java

It just needs 2 lines added to the grow method there, one for CropGrowEvent.Pre and one for CropGrowEvent.Post

**Comment by cweckerl** [comment]
Thanks! Done
