### ISSUE TITLE
Culinary Construct Compatability

### ISSUE THREAD

**Issue by Coffe-e** [cweckerl/simplefarming#92]
Adding the "bread" tag to breads such as Sorghum, Zucchini, Banana, and Cornbread, so that the culinary table recognizes them as valid breads to use in sandwich making.

**Comment by cweckerl** [comment]
Originally these items were tagged as bread, but I changed it in #83

**Comment by Coffe-e** [comment]
Ah, I understand. 
Maybe you could make it a config option? It's cool if not though.
Anyways, thanks for your response.
