### ISSUE TITLE
Fast Graphics breaks fruit tree textures if fruit is on the tree

### ISSUE THREAD

**Issue by dinoman9877** [cweckerl/simplefarming#93]
**Forge Version**
31.2.0
**Mod list (optional)**

**Log file (optional)**

**Describe the issue**
If you switch to fast graphics, the fruit tree leave texture becomes broken. It is fixed if you harvest the fruit.

![2020-07-20_21 40 39](https://user-images.githubusercontent.com/68574459/88003397-c416e880-cad2-11ea-8b27-f65f28bfb9e3.png)
![2020-07-20_21 40 43](https://user-images.githubusercontent.com/68574459/88003399-c4af7f00-cad2-11ea-98ca-b299cf5b5e09.png)

**Comment by cweckerl** [comment]
Thanks! I will look into this.
