### ISSUE TITLE
[1.16.1] Forge 32.0.90+ breaks this mod. (Forge issue)

### ISSUE THREAD

**Issue by 04Slash** [cweckerl/simplefarming#96]
**Forge Version**
32.0.90 to 32.0.92 cause an instant crash.
32.0.93 gives [this](https://imgur.com/w8mlYyt) screen and the below lastest.log.
**Everything works just fine on forge 32.0.88.**

**Mod list (optional)**
simplefarming-1.16.1-1.3.1.jar
No other mods present.

**Log file (optional)**
No crash report was created.
[Latest.log](https://pastebin.com/SDD5mX8G)

**Describe the issue**
The game is crashing on load. By the looks of it, forge did some internal changes which breaks your mod. I am no coder, so don't take my word on that.

I'm going to leave this here because it may help people using google, so just ignore this.
Failed to create mod instance. ModID: simplefarming, class enemeez.simplefarming.SimpleFarming
java.lang.IllegalArgumentException: Cannot register a generic event listener with addListener, use addGenericListener

Update: While searching for other mods, this seems to be an issue with forge and not your mod.
Update 2: Jumped the gun a little too soon. This mod is still broken with forge 32.0.96. I will leave this open for now seeing as it's still an issue. You can feel free to close if you desire, seeing as this (probably) isn't an issue with your mod.
**If anyone has this issue, downgrading forge to 32.0.88 will fix this.**

**Comment by nepphhh** [comment]
Broken with forge 32.0.97 too.
